#!/usr/bin/ksh
Tmp="/tmp/$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1



ANON=`date`
print $ANON
print "Local Deployment..."
# tar cvf /tmp/Snips_$ANON.tar $HOME/.vim/Snips
cp ./* $HOME/.vim/Snips
